### ISSUE TITLE
Icons and labels in tabs are not aligned

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-material-styles#65]

**Comment by jouni** [comment]
If this is about the icons not being centered within the tabs in the vaadin-core-elements-ux app, then it’s an issue in [the app styles](https://github.com/vaadin/vaadin-core-elements-ux/blob/material/src/vaadin-core-elements-ux-app/vaadin-core-elements-ux-app.html#L23-L25) and not in the tabs theme, and this issue is invalid.

**Comment by jouni** [comment]
Closing as invalid.
