### ISSUE TITLE
Improve documentation / how to use

### ISSUE THREAD

**Issue by masbaehr** [vaadin/vaadin-material-styles#80]
Please improve the documentation how the Material theme can be used for Vaadin.
Especially without using bower or npm. 

e.g. I tried to change Lumo.class to Material.class but it does not work. There should be an easy way to use the theme.

I have added the packages to gradle
```gradle
compile group: 'com.vaadin', name: 'vaadin-material-theme', version: '1.2.3'
    compile group: 'org.webjars.bowergithub.vaadin', name: 'vaadin-material-styles', version: '1.2.0'
```

Now i know it was because i was using Vaadin11 so it should be noted somewhere that it only works with Vaadin 12 out of the box!

**Comment by web-padawan** [comment]
This issue was moved to vaadin/flow-and-components-documentation#368

**Comment by web-padawan** [comment]
Thanks for the issue, moved it to the proper repository so that our teammates could handle it.

Sorry for the inconvenience, we had to make some changes for ES modules conversion compatibility in scope of the same minor releases which shipped the Material theme. That's why the versions of components supporting Material theme are not compatible with V10. 

Regarding V11, the support for it will be ended as of 1.01.2019 so we encourage you to move to V12 now, apart from Material theme it has some performance improvements etc.
